# Generated by Django 4.0.2 on 2022-02-27 11:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CardHolder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('slug', models.SlugField(unique=True)),
                ('time', models.DateTimeField(null=True)),
                ('round_number', models.IntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
                ('started', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Round',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_triumph_source', models.CharField(choices=[('S', 'Solar'), ('W', 'Wind'), ('A', 'Atomic'), ('C', 'Carbon')], max_length=1)),
                ('round_number', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='GlobalCardDeck',
            fields=[
                ('cardholder_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='suena1M.cardholder')),
            ],
            bases=('suena1M.cardholder',),
        ),
        migrations.CreateModel(
            name='PlayersCollectedDeck',
            fields=[
                ('cardholder_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='suena1M.cardholder')),
                ('user', models.CharField(max_length=256)),
            ],
            bases=('suena1M.cardholder',),
        ),
        migrations.CreateModel(
            name='PriorityDeck',
            fields=[
                ('cardholder_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='suena1M.cardholder')),
            ],
            bases=('suena1M.cardholder',),
        ),
        migrations.CreateModel(
            name='Table',
            fields=[
                ('cardholder_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='suena1M.cardholder')),
            ],
            bases=('suena1M.cardholder',),
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('value', models.IntegerField(default=0)),
                ('source', models.CharField(choices=[('S', 'Solar'), ('W', 'Wind'), ('A', 'Atomic'), ('C', 'Carbon')], max_length=1)),
                ('forecast', models.CharField(choices=[('W', 'Weather'), ('M', 'Market'), ('N', 'Non')], max_length=1)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='suena1M.game')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='suena1M.cardholder')),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('cardholder_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='suena1M.cardholder')),
                ('name', models.CharField(max_length=256)),
                ('score', models.IntegerField(default=0)),
                ('source', models.IntegerField(default=0)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='suena1M.game')),
            ],
            bases=('suena1M.cardholder',),
        ),
    ]
