# Generated by Django 4.0.2 on 2022-03-10 20:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CardHolder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('slug', models.SlugField(unique=True)),
                ('created', models.DateTimeField(editable=False)),
                ('modified', models.DateTimeField()),
                ('round_hour_number', models.IntegerField(default=0)),
                ('round_day_number', models.IntegerField(default=0)),
                ('turn_hour_player', models.IntegerField(default=0)),
                ('turn_day_player', models.IntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
                ('started', models.BooleanField(default=False)),
                ('current_domination', models.CharField(blank=True, choices=[('S', 'Solar'), ('W', 'Wind'), ('A', 'Atomic'), ('C', 'Carbon')], max_length=1, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PlayersCollectedDeck',
            fields=[
                ('cardholder_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='suena1M.cardholder')),
                ('user', models.CharField(max_length=256)),
            ],
            bases=('suena1M.cardholder',),
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('value', models.IntegerField(choices=[(0, 'Neun'), (10, 'Zehn'), (2, 'Bube'), (3, 'Dame'), (4, 'King'), (11, 'Ass')])),
                ('source', models.CharField(choices=[('S', 'Solar'), ('W', 'Wind'), ('A', 'Atomic'), ('C', 'Carbon')], max_length=1)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='suena1M.game')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='suena1M.cardholder')),
            ],
        ),
        migrations.CreateModel(
            name='Table',
            fields=[
                ('cardholder_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='suena1M.cardholder')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='suena1M.game')),
            ],
            bases=('suena1M.cardholder',),
        ),
        migrations.CreateModel(
            name='PriorityDeck',
            fields=[
                ('cardholder_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='suena1M.cardholder')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='suena1M.game')),
            ],
            bases=('suena1M.cardholder',),
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('cardholder_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='suena1M.cardholder')),
                ('name', models.CharField(max_length=256)),
                ('dam', models.IntegerField(default=0)),
                ('idm', models.IntegerField(default=0)),
                ('round_score', models.IntegerField(default=0)),
                ('game_score', models.IntegerField(default=0)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='suena1M.game')),
            ],
            bases=('suena1M.cardholder',),
        ),
        migrations.CreateModel(
            name='GlobalCardDeck',
            fields=[
                ('cardholder_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='suena1M.cardholder')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='suena1M.game')),
            ],
            bases=('suena1M.cardholder',),
        ),
    ]
