# Generated by Django 4.0.2 on 2022-03-02 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suena1M', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='score',
            new_name='dam',
        ),
        migrations.RenameField(
            model_name='player',
            old_name='source',
            new_name='game_score',
        ),
        migrations.AddField(
            model_name='player',
            name='idm',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='round_score',
            field=models.IntegerField(default=0),
        ),
    ]
