# Generated by Django 4.0.2 on 2022-03-11 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suena1M', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='dam',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='idm',
            field=models.IntegerField(null=True),
        ),
    ]
