# Generated by Django 4.0.2 on 2022-03-08 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suena1M', '0002_alter_card_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='payers_turn',
            field=models.IntegerField(default=0),
        ),
    ]
