# Generated by Django 4.0.2 on 2022-03-14 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suena1M', '0002_alter_player_dam_alter_player_idm'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='splitted_cards_count',
            field=models.IntegerField(default=0),
        ),
    ]
