# Generated by Django 4.0.2 on 2022-03-02 22:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('suena1M', '0002_rename_score_player_dam_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='globalcarddeck',
            name='game',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='suena1M.game'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='prioritydeck',
            name='game',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='suena1M.game'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='table',
            name='game',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='suena1M.game'),
            preserve_default=False,
        ),
    ]
