# Generated by Django 4.0.2 on 2022-03-15 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suena1M', '0003_game_splitted_cards_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='last_played_round',
            field=models.IntegerField(default=0),
        ),
    ]
