# Generated by Django 4.0.2 on 2022-03-09 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suena1M', '0003_game_payers_turn'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Round',
        ),
        migrations.RenameField(
            model_name='game',
            old_name='payers_turn',
            new_name='round_day_number',
        ),
        migrations.AddField(
            model_name='game',
            name='turn_day_payers',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='game',
            name='turn_payers',
            field=models.IntegerField(default=0),
        ),
    ]
