# Generated by Django 4.0.2 on 2022-03-03 19:01

from django.db import migrations, models
import suena1M.models


class Migration(migrations.Migration):

    dependencies = [
        ('suena1M', '0003_globalcarddeck_game_prioritydeck_game_table_game'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='forecast',
            field=models.CharField(choices=[(suena1M.models.Forecast['W'], 'Weather'), (suena1M.models.Forecast['M'], 'Market'), (suena1M.models.Forecast['N'], 'Non')], max_length=1),
        ),
        migrations.AlterField(
            model_name='card',
            name='source',
            field=models.CharField(choices=[(suena1M.models.EnergySource['S'], 'Solar'), (suena1M.models.EnergySource['W'], 'Wind'), (suena1M.models.EnergySource['A'], 'Atomic'), (suena1M.models.EnergySource['C'], 'Carbon')], max_length=1),
        ),
        migrations.AlterField(
            model_name='round',
            name='current_triumph_source',
            field=models.CharField(choices=[(suena1M.models.EnergySource['S'], 'Solar'), (suena1M.models.EnergySource['W'], 'Wind'), (suena1M.models.EnergySource['A'], 'Atomic'), (suena1M.models.EnergySource['C'], 'Carbon')], max_length=1),
        ),
    ]
