# Generated by Django 4.0.2 on 2022-03-09 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('suena1M', '0004_delete_round_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='round_number',
            new_name='round_hour_number',
        ),
        migrations.RenameField(
            model_name='game',
            old_name='turn_day_payers',
            new_name='turn_day_player',
        ),
        migrations.RenameField(
            model_name='game',
            old_name='turn_payers',
            new_name='turn_hour_player',
        ),
    ]
