# Generated by Django 4.0.2 on 2022-02-24 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suena1K', '0002_rename_running_game_started_game_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='time',
            field=models.DateTimeField(null=True),
        ),
    ]
